
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     owner_id BIGINT,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TYPE IF NOT EXISTS status AS ENUM  ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED') ;

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date timestamp without time zone,
                                        end_date timestamp without time zone,
                                        item_id BIGINT,
                                        booker_id BIGINT,
                                        status status,
                                        CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        requestor_id BIGINT,
                                        description VARCHAR(255) NOT NULL,
                                        created timestamp without time zone,
                                        CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        text VARCHAR(255) NOT NULL,
                                        item_id BIGINT,
                                        author_id BIGINT,
                                        created timestamp without time zone,
                                        CONSTRAINT pk_comment PRIMARY KEY (id)
    );

ALTER TABLE requests
    ADD FOREIGN KEY (requestor_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE comments
    ADD FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE comments
    ADD FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD FOREIGN KEY (booker_id) REFERENCES users (id);

ALTER TABLE items
     ADD FOREIGN KEY (owner_id) REFERENCES users (id);